### ISSUE TITLE
Config file is expected in /.config

### ISSUE THREAD

**Issue by purpleKarrot** [sqitchers/docker-sqitch#11]
Apparently, `HOME` is set to `/`. Adding `-e HOME=$homedst \` to the `docker run` command fixes the issue.

**Comment by theory** [comment]
Yes, that's why I recommend the use of the [shell script](/sqitchers/docker-sqitch/blob/master/docker-sqitch.sh), which mounts the home directory of your host to the home directory inside the container.

**Comment by purpleKarrot** [comment]
I think you misunderstood. I *do* use the shell script from this repository and it correctly mounts the home directory to `/home`. But it does not set the `$HOME` environment variable to that directory.
Adding the line `-e HOME=$homedst \` in the shell script fixes the issue.

**Comment by theory** [comment]
```
 > docker run --rm -it --entrypoint /bin/bash sqitch/sqitch
sqitch@fcf30d54f372:/repo$ echo $HOME
/home
```

The default user for the Sqitch docker image is named `sqitch` and its home is set to `/home` [here](/sqitchers/docker-sqitch/blob/6a6c23d103da57f918ae003e6f6c43466e6dad5f/Dockerfile#L58). If you run the script as root, however, it connects as `root` instead of `sqitch` [here](/sqitchers/docker-sqitch/blob/6a6c23d103da57f918ae003e6f6c43466e6dad5f/docker-sqitch.sh#L51). This is as designed. Have I missed something?

**Comment by purpleKarrot** [comment]
> The default user for the Sqitch docker image is named sqitch and its home is set to /home here.

Instead of using the default user, the shell script forwards the user id from the host [here](https://github.com/sqitchers/docker-sqitch/blob/master/docker-sqitch.sh#L19). The user `sqitch` will be used if and only if the user id on the host is `1024`.

Consider this:

```
> docker run --rm -it -u 1000:985 --entrypoint /bin/bash sqitch/sqitch
I have no name!@bbc8b102fff9:/repo$ echo $HOME
/
```

**Comment by theory** [comment]
Bah, I forgot that I changed that behavior in cd14783. Thanks, will fix.
